base_platform: b-ubuntu-1204
topology: ha
api_fqdn: chef-ha.lxc
mounts:
  - /dev-shared dev-shared
packages:
  server: /dev-shared/chef-packages/ec/private-chef_11.1.2-1.ubuntu.12.04_amd64.deb
  reporting: /dev-shared/chef-packages/ec/reporting/opscode-reporting_1.1.0-1.ubuntu.12.04_amd64.deb
  push-jobs-server: /dev-shared/chef-packages/ec/push-jobs-server/opscode-push-jobs-server_1.1.0-1.ubuntu.12.04_amd64.deb
  manage: /dev-shared/chef-packages/ec/manage/opscode-manage_1.1.1-1.ubuntu.12.04_amd64.deb
servers:
  be1-ha.lxc:
    role: backend
    ipaddress: 10.0.3.206
    bootstrap: true
    cluster_ipaddress: 192.168.0.5
  be2-ha.lxc:
    role: backend
    ipaddress: 10.0.3.207
    cluster_ipaddress: 192.168.0.6
  fe1-ha.lxc:
    role: frontend
    ipaddress: 10.0.3.208
#  fe2-ha.lxc:
#    role: frontend
#    ipaddress: 10.0.3.209
backend_vip:
  be-ha.lxc:
    ipaddress: 10.0.3.210
    device: eth0
    heartbeat_device: eth1
