base_platform: b-ubuntu-1204
topology: open-source
api_fqdn: chef-osc.lxc
mounts:
  - /dev-shared dev-shared
packages:
  server: /dev-shared/chef-packages/osc/chef-server_11.0.10-1.ubuntu.12.04_amd64.deb
servers:
  chef-osc.lxc:
    ipaddress: 10.0.3.205
