platform_image: p-ubuntu-1204
topology: open-source
api_fqdn: chef.lxc
mounts:
  - /dev-shared dev-shared
packages:
  server: /dev-shared/chef-packages/osc/chef-server_11.1.6-1_amd64.deb
servers:
  osc-chef.lxc:
    ipaddress: 10.0.3.207
