## Mount source directories must exist in the LXC host

## Make sure package paths are correct

## All FQDNs and server names must end with the `.lxc` domain

## DHCP reserved (static) IPs must be selected from the IP range 10.0.3.150 - 254

chef-server:
  platform_image: p-ubuntu-1404
  mounts:
    - /dev-shared dev-shared
  packages:
    server: /dev-shared/chef-packages/cs/chef-server-core_12.0.7-1_amd64.deb
    manage: /dev-shared/chef-packages/manage/opscode-manage_1.11.2-1_amd64.deb
#    reporting: /dev-shared/chef-packages/reporting/opscode-reporting_1.2.3-1_amd64.deb
#    push-jobs-server: /dev-shared/chef-packages/push-jobs-server/opscode-push-jobs-server_1.1.6-1_amd64.deb

##   The chef-sync package would only be installed.
##   It would NOT be configured since we don't know whether it should be a master or replica.
#    sync: /dev-shared/chef-packages/sync/chef-sync_1.0.0~rc.6-1_amd64.deb

  api_fqdn: chef.lxc
  topology: standalone
  servers:
    chef.lxc:
      ipaddress: 10.0.3.201

analytics:
  platform_image: p-ubuntu-1404
  mounts:
    - /dev-shared dev-shared
  packages:
    analytics: /dev-shared/chef-packages/analytics/opscode-analytics_1.1.2-1_amd64.deb

  analytics_fqdn: analytics.lxc
  topology: standalone
  servers:
    analytics.lxc:
      ipaddress: 10.0.3.202
