## platform_image can be one of the following:
## p-centos-5, p-centos-6, p-ubuntu-1204 or p-ubuntu-1404

## Make sure a mount's source directory exists in the LXC host

## Make sure a package's path is correct

## All FQDNs and server names must end with the `.lxc` domain

## DHCP reserved (static) IPs must be selected from the IP range 10.0.3.150 - 254

## topology can be one of the following:
## standalone, tier or open-source (for the old open source 11 chef server)

chef-server:
  platform_image: p-ubuntu-1404
  mounts:
    - /root/dev root/dev
  packages:
    server: /root/dev/chef-packages/cs/chef-server-core_12.0.8-1_amd64.deb
    manage: /root/dev/chef-packages/manage/opscode-manage_1.12.0-1_amd64.deb
#    reporting: /root/dev/chef-packages/reporting/opscode-reporting_1.3.0-1_amd64.deb
#    push-jobs-server: /root/dev/chef-packages/push-jobs-server/opscode-push-jobs-server_1.1.6-1_amd64.deb
#    sync: /root/dev/chef-packages/sync/chef-sync_1.0.0~rc.6-1_amd64.deb

##   The chef-sync package will only be installed.
##   chef-sync will NOT be configured since we don't know whether it should be a master or replica.

  api_fqdn: chef.lxc
  topology: standalone
  servers:
    chef.lxc:
      ipaddress: 10.0.3.201

analytics:
  platform_image: p-ubuntu-1404
  mounts:
    - /root/dev root/dev
  packages:
    analytics: /root/dev/chef-packages/analytics/opscode-analytics_1.1.2-1_amd64.deb

  analytics_fqdn: analytics.lxc
  topology: standalone
  servers:
    analytics.lxc:
      ipaddress: 10.0.3.202
