## platform_image can be one of the following:
## p-centos-5, p-centos-6, p-ubuntu-1204 or p-ubuntu-1404

## Make sure a mount's source directory exists in the LXC host

## Make sure a package's path is correct

## All FQDNs and server names must end with the `.lxc` domain

## DHCP reserved (static) IPs must be selected from the IP range 10.0.3.150 - 254

## topology can be one of the following:
## standalone, tier or open-source (for the old open source 11 chef server)

chef-server:
  platform_image: p-ubuntu-1404
  mounts:
    - /dev-shared dev-shared
  packages:
    server: /dev-shared/chef-packages/cs/chef-server-core_12.0.7-1_amd64.deb
    manage: /dev-shared/chef-packages/manage/opscode-manage_1.11.2-1_amd64.deb
#    reporting: /dev-shared/chef-packages/reporting/opscode-reporting_1.2.3-1_amd64.deb
#    push-jobs-server: /dev-shared/chef-packages/push-jobs-server/opscode-push-jobs-server_1.1.6-1_amd64.deb

##   The chef-sync package would only be installed.
##   It would NOT be configured since we don't know whether it should be a master or replica.
#    sync: /dev-shared/chef-packages/sync/chef-sync_1.0.0~rc.6-1_amd64.deb

  api_fqdn: chef.lxc
  topology: tier
  servers:
    chef-be.lxc:
      role: backend
      ipaddress: 10.0.3.203
      bootstrap: true
    chef-fe1.lxc:
      role: frontend
      ipaddress: 10.0.3.204
#    chef-fe2.lxc:
#      role: frontend
#      ipaddress: 10.0.3.205

analytics:
  platform_image: p-ubuntu-1404
  mounts:
    - /dev-shared dev-shared
  packages:
    analytics: /dev-shared/chef-packages/analytics/opscode-analytics_1.1.2-1_amd64.deb

  analytics_fqdn: analytics.lxc
  topology: tier
  servers:
    analytics-be.lxc:
      role: backend
      ipaddress: 10.0.3.206
      bootstrap: true
    analytics-fe1.lxc:
      role: frontend
      ipaddress: 10.0.3.207
#    analytics-fe2.lxc:
#      role: frontend
#      ipaddress: 10.0.3.208
