platform_container: p-ubuntu-1404
topology: tier
api_fqdn: chef.lxc
#analytics_fqdn: analytics.lxc
mounts:
  - /dev-shared dev-shared
packages:
  server: /dev-shared/chef-packages/cs/chef-server-core_12.0.5-1_amd64.deb
#  manage: /dev-shared/chef-packages/manage/opscode-manage_1.11.2-1_amd64.deb
#  reporting: /dev-shared/chef-packages/reporting/opscode-reporting_1.2.3-1_amd64.deb
#  push-jobs-server: /dev-shared/chef-packages/push-jobs-server/opscode-push-jobs-server_1.1.6-1_amd64.deb
#  analytics: /dev-shared/chef-packages/analytics/opscode-analytics_1.1.1-1_amd64.deb
servers:
  tier-be.lxc:
    role: backend
    ipaddress: 10.0.3.203
    bootstrap: true
  tier-fe1.lxc:
    role: frontend
    ipaddress: 10.0.3.204
#  tier-fe2.lxc:
#    role: frontend
#    ipaddress: 10.0.3.205
#  tier-analytics.lxc:
#    role: analytics
#    ipaddress: 10.0.3.206